### ISSUE TITLE
Errors in Linux version

### ISSUE THREAD

**Issue by kortaol** [pixbits/lifecraft-issues#7]
Hello, Linux version has some errors:

```
Assertion Failed at /home/jack/Documents/lifecraft/pix/pix/io/FileHandle.h:152
Ошибка сегментирования (Segmentation Fault)
```

Probably you've used your path to file. A possible solution is to replace the full path with a short one (./pix/pix/io/FileHandle.h)

**Comment by Jakz** [comment]
No, the path you see is where the assert is launched in the code base, I guess this is permission related but we should investigate it further. I'll add some logging for the next alpha versions to better catch these issues.

**Comment by Jakz** [comment]
I've read your post in itch.io, so I consider this issue closed! :)

**Comment by kortaol** [comment]
Way to "fix": `chmod +x $(find /path/to/game)`
